import type { IconType } from 'react-icons';
import {
  FiActivity,
  FiAward,
  FiBookOpen,
  FiBriefcase,
  FiCoffee,
  FiCreditCard,
  FiDollarSign,
  FiDroplet,
  FiFileText,
  FiFilm,
  FiGift,
  FiGlobe,
  FiHeart,
  FiHome,
  FiMapPin,
  FiMonitor,
  FiMoreHorizontal,
  FiMusic,
  FiPackage,
  FiShield,
  FiShoppingBag,
  FiSmartphone,
  FiStar,
  FiTag,
  FiTool,
  FiTrendingUp,
  FiTruck,
  FiUmbrella,
  FiWifi,
  FiZap,
} from 'react-icons/fi';

/** Icon keys stored on categories / payment sources → react-icons (Feather) components */
export const ICONS: Record<string, IconType> = {
  food: FiCoffee,
  transport: FiTruck,
  home: FiHome,
  shopping: FiShoppingBag,
  health: FiHeart,
  fitness: FiActivity,
  entertainment: FiFilm,
  music: FiMusic,
  bills: FiFileText,
  utilities: FiZap,
  water: FiDroplet,
  internet: FiWifi,
  phone: FiSmartphone,
  education: FiBookOpen,
  travel: FiGlobe,
  place: FiMapPin,
  tech: FiMonitor,
  repair: FiTool,
  insurance: FiUmbrella,
  security: FiShield,
  parcel: FiPackage,
  tag: FiTag,
  star: FiStar,
  other: FiMoreHorizontal,
  salary: FiBriefcase,
  freelance: FiMonitor,
  business: FiAward,
  investment: FiTrendingUp,
  gift: FiGift,
  cash: FiDollarSign,
  upi: FiSmartphone,
  card: FiCreditCard,
  credit: FiCreditCard,
  bank: FiHome,
  wallet: FiCreditCard,
};

export const CATEGORY_ICON_KEYS = [
  'food',
  'transport',
  'home',
  'shopping',
  'health',
  'fitness',
  'entertainment',
  'music',
  'bills',
  'utilities',
  'water',
  'internet',
  'phone',
  'education',
  'travel',
  'place',
  'tech',
  'repair',
  'insurance',
  'security',
  'parcel',
  'tag',
  'star',
  'salary',
  'business',
  'investment',
  'gift',
  'other',
];
export const SOURCE_ICON_KEYS = ['cash', 'upi', 'card', 'credit', 'bank', 'wallet', 'phone', 'other'];

export const iconFor = (key?: string | null): IconType => (key && ICONS[key]) || FiMoreHorizontal;
