import { API_URL } from '@/config';
import type { TypedDocumentString } from '@/gql/graphql';

let token: string | null = null;
let onUnauthenticated: (() => void) | null = null;

export const setAuthToken = (value: string | null) => {
  token = value;
};
export const setUnauthenticatedHandler = (handler: (() => void) | null) => {
  onUnauthenticated = handler;
};

export class ApiError extends Error {
  readonly code: string | undefined;

  constructor(message: string, code?: string) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
  }
}

interface GqlResponse<T> {
  data?: T;
  errors?: { message: string; extensions?: { code?: string } }[];
}

async function post(body: string, timeoutMs: number): Promise<Response> {
  try {
    return await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json', ...(token && { Authorization: `Bearer ${token}` }) },
      body,
      signal: AbortSignal.timeout(timeoutMs),
    });
  } catch (err) {
    const timedOut = err instanceof DOMException && err.name === 'TimeoutError';
    throw new ApiError(timedOut ? 'The server took too long to respond.' : "Can't reach the Spentiva API. Check your connection.", 'NETWORK');
  }
}

/** Typed GraphQL request using documents generated by GraphQL Code Generator */
export async function gql<TResult, TVariables>(
  document: TypedDocumentString<TResult, TVariables>,
  variables?: TVariables,
  timeoutMs = 30_000,
): Promise<TResult> {
  const res = await post(JSON.stringify({ query: document.toString(), variables }), timeoutMs);
  let json: GqlResponse<TResult>;
  try {
    json = (await res.json()) as GqlResponse<TResult>;
  } catch {
    throw new ApiError(`Server error (${res.status})`, 'SERVER');
  }
  const first = json.errors?.[0];
  if (first) {
    if (first.extensions?.code === 'UNAUTHENTICATED') onUnauthenticated?.();
    throw new ApiError(first.message, first.extensions?.code);
  }
  if (!json.data) throw new ApiError('Empty response from the server', 'SERVER');
  return json.data;
}

export const errorMessage = (err: unknown) => (err instanceof Error ? err.message : 'Something went wrong');
