/**
 * Inlines the Chart.js UMD build into a TS module so charts render inside the
 * WebView without any network request (works offline, no CDN).
 * Run after upgrading chart.js:  npm run gen:chartjs
 */
const fs = require('node:fs');
const path = require('node:path');

const pkgDir = path.join(__dirname, '..', 'node_modules', 'chart.js');
const src = fs.readFileSync(path.join(pkgDir, 'dist', 'chart.umd.min.js'), 'utf8').replaceAll('</script', String.raw`<\/script`);
const { version } = JSON.parse(fs.readFileSync(path.join(pkgDir, 'package.json'), 'utf8'));
const out = path.join(__dirname, '..', 'src', 'components', 'chart', 'chartjs.generated.ts');

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `/* eslint-disable */\n// Generated by scripts/gen-chartjs.js from chart.js@${version}. Do not edit.\nexport const CHART_JS_VERSION = ${JSON.stringify(version)};\nexport const CHART_JS_SOURCE = ${JSON.stringify(src)};\n`,
);
console.log(`Wrote ${path.relative(process.cwd(), out)} (chart.js@${version}, ${(src.length / 1024).toFixed(0)} KB)`);
