import Constants from 'expo-constants';
import * as SecureStore from 'expo-secure-store';
import type { TypedDocumentString } from '@/gql/graphql';

const API_URL_KEY = 'spentiva.apiUrl';

/** Built-in GraphQL endpoint (EXPO_PUBLIC_API_URL at build time, see app.config.ts) */
export const DEFAULT_API_URL = String(Constants.expoConfig?.extra?.apiUrl ?? '');

let apiUrl = DEFAULT_API_URL;
let token: string | null = null;
let onUnauthenticated: (() => void) | null = null;

export const getApiUrl = () => apiUrl;
export const setAuthToken = (value: string | null) => {
  token = value;
};
export const setUnauthenticatedHandler = (handler: (() => void) | null) => {
  onUnauthenticated = handler;
};

/** Server URL override (Login → Server) so one build can point at any Spentiva API */
export async function loadApiUrl() {
  apiUrl = (await SecureStore.getItemAsync(API_URL_KEY)) ?? DEFAULT_API_URL;
  return apiUrl;
}

export async function saveApiUrl(url: string | null) {
  if (url && url !== DEFAULT_API_URL) await SecureStore.setItemAsync(API_URL_KEY, url);
  else await SecureStore.deleteItemAsync(API_URL_KEY);
  apiUrl = url ?? DEFAULT_API_URL;
}

export class ApiError extends Error {
  readonly code: string | undefined;

  constructor(message: string, code?: string) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
  }
}

interface GqlResponse<T> {
  data?: T;
  errors?: { message: string; extensions?: { code?: string } }[];
}

async function post(body: string, timeoutMs: number): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json', ...(token && { Authorization: `Bearer ${token}` }) },
      body,
      signal: controller.signal,
    });
  } catch (err) {
    const timedOut = (err as Error).name === 'AbortError';
    throw new ApiError(timedOut ? 'The server took too long to respond.' : "Can't reach the server. Check your internet connection.", 'NETWORK');
  } finally {
    clearTimeout(timer);
  }
}

/** Typed GraphQL request using documents generated by GraphQL Code Generator */
export async function gql<TResult, TVariables>(
  document: TypedDocumentString<TResult, TVariables>,
  variables?: TVariables,
  timeoutMs = 30_000,
): Promise<TResult> {
  const res = await post(JSON.stringify({ query: document.toString(), variables }), timeoutMs);
  let json: GqlResponse<TResult>;
  try {
    json = (await res.json()) as GqlResponse<TResult>;
  } catch {
    throw new ApiError(`Server error (${res.status})`, 'SERVER');
  }
  const first = json.errors?.[0];
  if (first) {
    if (first.extensions?.code === 'UNAUTHENTICATED') onUnauthenticated?.();
    throw new ApiError(first.message, first.extensions?.code);
  }
  if (!json.data) throw new ApiError('Empty response from server', 'SERVER');
  return json.data;
}

export const errorMessage = (err: unknown) => (err instanceof Error ? err.message : 'Something went wrong');
