import type {
  CategoryFieldsFragment,
  ChatFieldsFragment,
  DashboardQuery,
  EnvFieldsFragment,
  ReferenceQuery,
  ReportFieldsFragment,
  SlackChannelsQuery,
  SliceFieldsFragment,
  SourceFieldsFragment,
  TicketFieldsFragment,
  TxFieldsFragment,
  UserFieldsFragment,
  ValidationRulesQuery,
} from '@/gql/graphql';

/** App-facing names for the types generated by GraphQL Code Generator */
export type {
  ChartType,
  ChatKind,
  ChatRole,
  EnvSource,
  Period,
  ReportInput,
  ReportKind,
  StatFormat,
  TicketCategory,
  TicketStatus,
  TransactionFilter,
  TransactionInput,
  TxType,
} from '@/gql/graphql';

export type User = UserFieldsFragment;
export type Category = CategoryFieldsFragment;
export type ExpenseOn = Category['items'][number];
export type PaymentSource = SourceFieldsFragment;
export type Transaction = TxFieldsFragment;
export type Report = ReportFieldsFragment;
export type Stat = Report['stats'][number];
export type CategorySlice = SliceFieldsFragment;
export type Dashboard = DashboardQuery['dashboard'];
/** `pending` marks an optimistic message that the server hasn't confirmed yet */
export type ChatMessage = ChatFieldsFragment & { pending?: boolean };
export type ChatOption = ChatFieldsFragment['options'][number];
export type EnvVar = EnvFieldsFragment;
export type SlackChannel = SlackChannelsQuery['slackChannels'][number];
export type Currency = ReferenceQuery['currencies'][number];
export type SupportTicket = TicketFieldsFragment;
export type TicketMessage = SupportTicket['messages'][number];
/** Form limits the API enforces (validationRules) */
export type ValidationRules = ValidationRulesQuery['validationRules'];
